name: Notify New Issues

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run webhook curl command
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_ISSUE_WEBHOOK_URL }}
          # GITHUB_CONTEXT: ${{toJson(github)}}
          ISSUE: ${{toJson(github.event.issue.title)}}
        shell: bash
        run: echo $ISSUE | sed 's/[^a-zA-Z0-9 &().,:]//g' | xargs -I {} curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json" --data '{"issue":"{}", "issueTitle":"${{github.event.issue.title}}", "issueUrl":"${{github.event.issue.html_url}}", "issueAuthor":"${{github.event.issue.user.login}}", "issueNumber":"${{github.event.issue.number}}", "issueCreateTime":"${{github.event.issue.created_at}}"}'
