name: "aws-bugbounty"
on:
  pull_request_target:
  
jobs:
  build_image_prediction_tutorial:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Env Vars
        uses: ./.github/actions/setup-env-vars
