name: "Gitflow Enforcer Bot"
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  non-release-pr:
    runs-on: ubuntu-latest
    if: "!contains(github.head_ref, 'release/')"
    steps:
      - name: Fail Check
        run: |
          echo "not a release branch: ${{ github.head_ref }}"
          exit 1
