name: Version - Tag

on:
  push:
jobs:
  tag_merged_version:
    if: startsWith(github.event.head_commit.message, 'v')
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Tag Value
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "COMMIT_MSG"

