name: "Gitflow Enforcer Bot"
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  non-release-pr:
    runs-on: ubuntu-latest
    if: "!contains(github.head_ref, 'release/')"
    steps:
      - name: Post Warning
        uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ⚠️  **Error:** only release PRs should be merged into `main`, feature PRs should use `develop`
            See our [Contributing Guide](https://github.com/${{ github.repository }}/blob/develop/CONTRIBUTING.md#git-workflow) for more information.
          check_for_duplicate_msg: true
      - name: Fail Check
        run: |
          echo "not a release branch: ${{ github.head_ref }}"
          exit 1
